# Generated by Django 4.2.6 on 2024-01-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticket_priority_ticket_workplace_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('Problem nie wpływa na prace przy stanowisku', 'Problem nie wpływa na prace przy stanowisku'), ('Problem utrudnia pracę przy stanowisku', 'Problem utrudnia pracę przy stanowisku'), ('Problem uniemożliwia pracę przy stanowisku', 'Problem uniemożliwia pracę przy stanowisku')], default='Not Affecting', max_length=120),
        ),
    ]
